"""
tools/task2_turn_report.py -- table + figure from the turn-trial JSONL logs.

Written by Student B (assist) for Student A's Task 2 evidence, pending review
by Student A.

Reads every docs/report_assets/task2/logs/turn_trials_*.jsonl written by
tools/task2_turn_trials.py and regenerates, from those logs only:
  docs/report_assets/task2/turn_accuracy_table.md
  docs/report_assets/task2/turn_accuracy.png

No simulator needed:
  .venv/bin/python tools/task2_turn_report.py
"""

import json
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "docs" / "report_assets" / "task2"
LOGS = ASSETS / "logs"

MODES = [  # (key, short label, long description)
    ("closed", "Closed-loop turn()",
     "RealSkills.turn(angle): P-control on get_robot_pose() yaw, kp=1, |wz|<=1, exits at |err|<=2 deg"),
    ("open_A", "Open-loop, A's mapping",
     "move(0,0,0.6,t), t = 1.5 s x angle/90 (assumes 60 deg/s at wz=0.6; skills_real.py --compare-turn)"),
    ("open_cal", "Open-loop, calibrated",
     "move(0,0,0.6,t), t = angle / r_cal, r_cal measured in the same run (3 x 4 s at wz=0.6)"),
]
# Reference palette slots 1-3 (dataviz skill, validated all-pairs), neutral ink.
COLORS = {"closed": "#2a78d6", "open_A": "#eb6834", "open_cal": "#1baf7a"}
INK, INK2, GRID, SURFACE = "#0b0b0b", "#52514e", "#e4e3df", "#fcfcfb"


def load():
    rows = []
    files = sorted(LOGS.glob("turn_trials_*.jsonl"))
    for f in files:
        for line in f.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                r["_file"] = f.name
                rows.append(r)
    return rows, files


def sd(xs):
    return st.stdev(xs) if len(xs) > 1 else 0.0


def summarise(rows):
    out = []
    targets = sorted({r["target_deg"] for r in rows if r["mode"] != "cal"},
                     key=lambda a: (a < 0, abs(a)))
    for tgt in targets:
        for key, label, _ in MODES:
            g = [r for r in rows if r["mode"] == key and r["target_deg"] == tgt]
            if not g:
                continue
            abs_e = [r["abs_error_deg"] for r in g]
            out.append({
                "target": tgt, "mode": key, "label": label, "n": len(g),
                "abs_mean": st.mean(abs_e), "abs_sd": sd(abs_e), "abs_max": max(abs_e),
                "signed_mean": st.mean(r["heading_error_deg"] for r in g),
                "rot_mean": st.mean(r["rotation_deg"] for r in g),
                "absrot_mean": st.mean(abs(r["rotation_deg"]) for r in g),
                "cmd_t": st.mean(r["cmd_sim_s"] for r in g),
                "settle": st.mean(r["settle_time_s"] for r in g),
                "wall": st.mean(r["wall_time_s"] for r in g),
                "printed": ([r["turn_printed_final_error_deg"] for r in g]
                            if key == "closed" else None),
                "cw": sum(1 for r in g if r["rotation_deg"] < 0),
                "ccw": sum(1 for r in g if r["rotation_deg"] > 0),
                "files": sorted({r["_file"] for r in g}),
            })
    return out


def table_md(rows, summ, files):
    cal = [r for r in rows if r["mode"] == "cal"]
    runs = sorted({(r["_file"], r["run_id"], r.get("cal_rate_deg_s")) for r in rows
                   if r["mode"] != "cal"})
    loads = [r.get("loadavg_1m") for r in rows if r.get("loadavg_1m") is not None]
    rtf = [r["rt_factor"] for r in rows if r.get("rt_factor")]
    L = ["# Task 2 -- open-loop vs closed-loop turn accuracy", "",
         "Generated by `tools/task2_turn_report.py` from "
         + ", ".join(f"`logs/{f.name}`" for f in files)
         + ". Do not edit by hand; re-run the script.", "",
         "Every trial starts from a settled stand and is scored after the robot has "
         "settled again (yaw peak-to-peak < 0.2 deg over 0.5 s of sim time). "
         "`|error|` = |wrap(final yaw - start yaw - target)|, from an unwrapped yaw "
         "track sampled at ~200 Hz. Mean ± sample std over n trials. Positive = left "
         "(counter-clockwise). `turned L/R` counts the actual direction of rotation.", "",
         "| Target | Mode | n | mean \\|error\\| ± std (deg) | max \\|error\\| (deg) "
         "| mean signed error (deg) | mean \\|rotation\\| (deg, % of target) | turned L/R "
         "| command time, sim (s) | settle after cmd (s) | wall time / trial (s) |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for s in summ:
        L.append(
            f"| {s['target']:+.0f} | {s['label']} | {s['n']} "
            f"| {s['abs_mean']:.2f} ± {s['abs_sd']:.2f} | {s['abs_max']:.2f} "
            f"| {s['signed_mean']:+.2f} | {s['absrot_mean']:.1f} "
            f"({100 * s['absrot_mean'] / abs(s['target']):.0f}%) | {s['ccw']}/{s['cw']} "
            f"| {s['cmd_t']:.2f} | {s['settle']:.2f} | {s['wall']:.2f} |")
    L += ["", "Modes:", ""]
    for key, label, desc in MODES:
        L.append(f"- **{label}** (`{key}`): {desc}.")
    L += ["", "Calibration and run conditions:", ""]
    for f, rid, rate in runs:
        cr = [r for r in cal if r["run_id"] == rid]
        if rate:
            L.append(f"- `{f}` (run `{rid}`): r_cal = {rate:.2f} deg/s at wz = 0.6 "
                     f"(rotations {', '.join(f'{abs(r['rotation_deg']):.1f}' for r in cr)} "
                     f"deg over 4.0 s each; nominal 0.6 rad/s = 34.4 deg/s).")
        else:
            L.append(f"- `{f}` (run `{rid}`).")
    if loads:
        L.append(f"- 1-min load average during trials: {min(loads):.2f}-{max(loads):.2f} "
                 f"(32-core host); sim real-time factor during commands "
                 f"{min(rtf):.2f}-{max(rtf):.2f} (sim s / wall s).")
    closed = [s for s in summ if s["mode"] == "closed"]
    if closed:
        L += ["", "Closed-loop details:", ""]
        for s in closed:
            pe = [abs(p) for p in s["printed"] if p is not None]
            L.append(
                f"- {s['target']:+.0f} deg: `[TURN]` line printed mean |final_error| "
                f"{st.mean(pe):.2f} deg (error at loop exit, bounded by the 2 deg "
                f"tolerance) vs {s['abs_mean']:.2f} deg after settling; "
                f"direction: {s['ccw']} left / {s['cw']} right.")
    return "\n".join(L) + "\n"


def figure(summ, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    targets = sorted({s["target"] for s in summ}, key=lambda a: (a < 0, abs(a)))
    plt.rcParams.update({"font.size": 10, "axes.edgecolor": INK2,
                         "axes.labelcolor": INK, "xtick.color": INK2,
                         "ytick.color": INK2, "text.color": INK})
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.2), facecolor=SURFACE,
                             gridspec_kw={"width_ratios": [1.35, 1]})
    panels = [(axes[0], ["closed", "open_A", "open_cal"],
               "(a) All modes"),
              (axes[1], ["closed", "open_cal"],
               "(b) Zoom: closed-loop vs calibrated open-loop")]
    labels = {k: lab for k, lab, _ in MODES}
    for ax, keys, title in panels:
        ax.set_facecolor(SURFACE)
        keys = [k for k in keys if any(s["mode"] == k for s in summ)]
        w = 0.8 / max(1, len(keys))
        for i, k in enumerate(keys):
            xs, ms, sds = [], [], []
            for j, t in enumerate(targets):
                s = next((s for s in summ if s["mode"] == k and s["target"] == t), None)
                if s:
                    xs.append(j + (i - (len(keys) - 1) / 2) * w)
                    ms.append(s["abs_mean"])
                    sds.append(s["abs_sd"])
            ax.bar(xs, ms, width=w - 0.03, color=COLORS[k], label=labels[k],
                   edgecolor=SURFACE, linewidth=2, zorder=2)
            ax.errorbar(xs, ms, yerr=sds, fmt="none", ecolor=INK, elinewidth=1.2,
                        capsize=3, zorder=3)
            # panel (a): label only the large open-loop bars (the small ones are
            # labelled in the zoom panel), to avoid overlapping labels
            for x, m, e in zip(xs, ms, sds) if (k == "open_A" or "open_A" not in keys) else []:
                ax.annotate(f"{m:.1f}", (x, m + e), xytext=(0, 3),
                            textcoords="offset points", ha="center", va="bottom",
                            fontsize=8, color=INK2)
        ax.set_xticks(range(len(targets)))
        ax.set_xticklabels([f"{t:+.0f}°" for t in targets])
        ax.set_xlabel("Commanded turn (left = +)")
        ax.set_ylabel("Mean |heading error| after settling (deg)")
        ax.set_title(title, fontsize=10, color=INK, loc="left")
        ax.grid(axis="y", color=GRID, linewidth=0.8, zorder=0)
        ax.set_axisbelow(True)
        for sp in ("top", "right"):
            ax.spines[sp].set_visible(False)
        ax.set_ylim(0, ax.get_ylim()[1] * 1.08)
    h, lab = axes[0].get_legend_handles_labels()
    fig.legend(h, lab, loc="upper center", ncol=3, frameon=False,
               bbox_to_anchor=(0.5, 1.0))
    n = max(s["n"] for s in summ)
    fig.text(0.5, 0.005, f"Error bars: ±1 sample std, n = {n} trials per bar. "
             "Source: docs/report_assets/task2/logs/turn_trials_*.jsonl",
             ha="center", fontsize=8, color=INK2)
    fig.tight_layout(rect=(0, 0.03, 1, 0.92))
    fig.savefig(path, dpi=160, facecolor=SURFACE)
    plt.close(fig)


def main():
    rows, files = load()
    if not rows:
        sys.exit(f"no logs in {LOGS}")
    summ = summarise(rows)
    (ASSETS / "turn_accuracy_table.md").write_text(table_md(rows, summ, files))
    figure(summ, ASSETS / "turn_accuracy.png")
    print((ASSETS / "turn_accuracy_table.md").read_text())


if __name__ == "__main__":
    main()
